version: '3.1'

services:

  frontend:
    image: 'frontend'
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:8080
    environment:
      - PORT=8080